trigger:
  branches:
    include:
      - main
      - uat
      - develop

pool:
  vmImage: ubuntu-latest
  name: 'Default'

# select variable group based on the branch being built
variables:
  - ${{ if eq(variables['Build.SourceBranchName'], 'main') }}:
    - group: anypoint-prod
    - name: mavenExtraArgs
      value: versions:set -DremoveSnapshot=true -DgenerateBackupPoms=false -DinteractiveMode=false
  - ${{ elseif eq( variables['Build.SourceBranchName'], 'uat' ) }}:
    - group: anypoint-uat
    - name: mavenExtraArgs
      value: 
  - ${{ else }}:
    - group: anypoint-dev
    - name: mavenExtraArgs
      value: 

jobs:
  - job: CleanWorkspaceJob
    workspace:
      clean: all
  - job: BuildAndDeployJob
steps:

- task: Cache@2
  displayName: Cache Maven Repo
  inputs:
    key: $(Build.SourcesDirectory)/pom.xml
    path: $(Pipeline.Workspace)/.m2/repository
  
- task: DownloadSecureFile@1
  displayName: 'secure file settings'
  inputs:
    secureFile: 'settings.xml'

    - task: Maven@4
      displayName: 'Clean project'
      inputs:
        mavenPomFile: 'pom.xml'  
        javaHomeOption: "JDKVersion"
        jdkVersionOption: "1.8"
        jdkArchitectureOption: "x64"    
        goals: 'clean $(mavenExtraArgs)'
        options: -s $(Agent.TempDirectory)/settings.xml
      timeoutInMinutes: 20

    - task: Maven@4
      displayName: 'Deploy to Anypoint Exchange'
  inputs:
    mavenPomFile: 'pom.xml'
        javaHomeOption: "JDKVersion"
        jdkVersionOption: "1.8"
        jdkArchitectureOption: "x64"    
        goals: 'deploy'
        options: -s $(Agent.TempDirectory)/settings.xml
      timeoutInMinutes: 20

    - task: Maven@4
      displayName: 'Deploy to Anypoint Runtime Manager'
  inputs:
    mavenPomFile: 'pom.xml'  
    javaHomeOption: "JDKVersion"
    jdkVersionOption: "1.8"
    jdkArchitectureOption: "x64"    
        goals: 'verify'
        options: >
          mule:deploy -U -V -e -B -s $(Agent.TempDirectory)/settings.xml
          -Dmule.artifact=dummy.jar
          -Dconnectedapp.client_id=$(connectedapp.client_id)
          -Dconnectedapp.client_secret=$(connectedapp.client_secret)
          -Danypoint.platform.client_id=$(anypoint.platform.client_id)
          -Danypoint.platform.client_secret=$(anypoint.platform.client_secret)
          -Dsecure.key=$(secure.key)
          -Ddeployment.env=$(deployment.env)
          -Ddeployment.prefix=$(deployment.prefix)
          -P$(deployment.env)
  timeoutInMinutes: 20