api:
  id: "1234"  # Auto-discovery

# The main flow of the API 
autodiscovery.flow: "main"

log:
  payload.maxSize: "4096"    
  attributes: "requestPath, method, queryString"

https:
  listener:
    host: "0.0.0.0"
    timeout:
      connection-idle: "40000"
  request:
    timeout:
      response: "10000"
      
tls:
  insecure: "true"
  type: "JCEKS"
  path: "keystores/mule.jceks"
  alias: "mule"
  key-password: "mule"
  password: "mule"
  
