api:
  id: "1234"  # Auto-discovery

# The main flow of the API 
autodiscovery.flow: "main"

log:
  payload.maxSize: "4096"    
  attributes: "requestPath, method, queryString"

http:
  port: "8081"  # this is needed for local only
  listener:
    timeout:
      connection-idle: "40000"
  request:
    timeout:
      response: "10000"