api:
  id: "1234"  # Auto-discovery

# The main flow of the API 
autodiscovery.flow: "main"

log:
  payload: "true"    
  attributes: "requestPath, method, queryString"

https:
  listener:
    host: "0.0.0.0"
    timeout:
      connection-idle: "600000"
  private:
    port: "8092"
  port: "8082"
  request:
    timeout:
      connection-idle: "400000"
      response: "40000"
      
tls:
  insecure: "true"
  type: "JCEKS"
  path: "tls/mule.jceks"
  alias: "mule"
  key-password: "mule"
  password: "mule"
  
